[build]
# Enable parallel compilation - use number of CPU cores
jobs = 16  # My CPU Cores

[net]
# Use multiple Git sources for faster dependency downloads
git-fetch-with-cli = true

[profile.dev]
# Enable incremental compilation
incremental = true
# Use more codegen units for parallel compilation
codegen-units = 256
# Optimize a bit even in debug mode
opt-level = 1
# Disable debug info for faster compilation
debug = false

[profile.release]
# Optimize for speed
opt-level = 3
# Use thin LTO for faster linking
lto = "thin"
# Single codegen unit for better optimization
codegen-units = 1 